baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ding YuChen"
theme = "hugo-PaperMod"

enableRobotsTXT = true

[menu]

[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about-me/"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowReadingTime = true
ShowShareButtons = true

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my personal blog!"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/ding-yuchen-181815140/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dingyuchen"